package com.wewin.mapper;

import com.wewin.entity.GroupInfo;
import com.wewin.entity.GroupInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface GroupInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group
     *
     * @mbggenerated Wed Dec 13 22:08:03 CST 2017
     */
    int countByExample(GroupInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group
     *
     * @mbggenerated Wed Dec 13 22:08:03 CST 2017
     */
    int deleteByExample(GroupInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group
     *
     * @mbggenerated Wed Dec 13 22:08:03 CST 2017
     */
    int deleteByPrimaryKey(Integer groupId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group
     *
     * @mbggenerated Wed Dec 13 22:08:03 CST 2017
     */
    int insert(GroupInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group
     *
     * @mbggenerated Wed Dec 13 22:08:03 CST 2017
     */
    int insertSelective(GroupInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group
     *
     * @mbggenerated Wed Dec 13 22:08:03 CST 2017
     */
    List<GroupInfo> selectByExample(GroupInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group
     *
     * @mbggenerated Wed Dec 13 22:08:03 CST 2017
     */
    GroupInfo selectByPrimaryKey(Integer groupId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group
     *
     * @mbggenerated Wed Dec 13 22:08:03 CST 2017
     */
    int updateByExampleSelective(@Param("record") GroupInfo record, @Param("example") GroupInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group
     *
     * @mbggenerated Wed Dec 13 22:08:03 CST 2017
     */
    int updateByExample(@Param("record") GroupInfo record, @Param("example") GroupInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group
     *
     * @mbggenerated Wed Dec 13 22:08:03 CST 2017
     */
    int updateByPrimaryKeySelective(GroupInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group
     *
     * @mbggenerated Wed Dec 13 22:08:03 CST 2017
     */
    int updateByPrimaryKey(GroupInfo record);
}