package com.wewin.mapper;

import com.wewin.entity.HomeWork;
import com.wewin.entity.HomeWorkExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface HomeWorkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table homework
     *
     * @mbggenerated Thu Jan 25 13:08:06 GMT+08:00 2018
     */
    int countByExample(HomeWorkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table homework
     *
     * @mbggenerated Thu Jan 25 13:08:06 GMT+08:00 2018
     */
    int deleteByExample(HomeWorkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table homework
     *
     * @mbggenerated Thu Jan 25 13:08:06 GMT+08:00 2018
     */
    int deleteByPrimaryKey(Integer homeworkno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table homework
     *
     * @mbggenerated Thu Jan 25 13:08:06 GMT+08:00 2018
     */
    int insert(HomeWork record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table homework
     *
     * @mbggenerated Thu Jan 25 13:08:06 GMT+08:00 2018
     */
    int insertSelective(HomeWork record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table homework
     *
     * @mbggenerated Thu Jan 25 13:08:06 GMT+08:00 2018
     */
    List<HomeWork> selectByExample(HomeWorkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table homework
     *
     * @mbggenerated Thu Jan 25 13:08:06 GMT+08:00 2018
     */
    HomeWork selectByPrimaryKey(Integer homeworkno);
    List<HomeWork> selectByOpenid(String openid);
    List<HomeWork> selectByTargetclass(String targetclass);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table homework
     *
     * @mbggenerated Thu Jan 25 13:08:06 GMT+08:00 2018
     */
    int updateByExampleSelective(@Param("record") HomeWork record, @Param("example") HomeWorkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table homework
     *
     * @mbggenerated Thu Jan 25 13:08:06 GMT+08:00 2018
     */
    int updateByExample(@Param("record") HomeWork record, @Param("example") HomeWorkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table homework
     *
     * @mbggenerated Thu Jan 25 13:08:06 GMT+08:00 2018
     */
    int updateByPrimaryKeySelective(HomeWork record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table homework
     *
     * @mbggenerated Thu Jan 25 13:08:06 GMT+08:00 2018
     */
    int updateByPrimaryKey(HomeWork record);

    /**
     * 删除班级相关作业 和 作业成员信息
     * @param classid
     * @return
     */
    int deleteClassHomework(Integer classid);
}