package com.wewin.mapper;

import com.wewin.entity.NoticeMember;
import org.springframework.stereotype.Repository;

@Repository
public interface NoticeMemberMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table noticemember
     *
     * @mbggenerated Wed Jan 24 13:41:17 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table noticemember
     *
     * @mbggenerated Wed Jan 24 13:41:17 CST 2018
     */
    int insert(NoticeMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table noticemember
     *
     * @mbggenerated Wed Jan 24 13:41:17 CST 2018
     */
    int insertSelective(NoticeMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table noticemember
     *
     * @mbggenerated Wed Jan 24 13:41:17 CST 2018
     */
    NoticeMember selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table noticemember
     *
     * @mbggenerated Wed Jan 24 13:41:17 CST 2018
     */
    int updateByPrimaryKeySelective(NoticeMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table noticemember
     *
     * @mbggenerated Wed Jan 24 13:41:17 CST 2018
     */
    int updateByPrimaryKey(NoticeMember record);
}