package com.wewin.entity;

import org.springframework.stereotype.Component;

import java.util.ArrayList;
import java.util.List;
@Component
public class ClassInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table class
     *
     * @mbggenerated Wed Dec 13 20:47:36 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table class
     *
     * @mbggenerated Wed Dec 13 20:47:36 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table class
     *
     * @mbggenerated Wed Dec 13 20:47:36 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class
     *
     * @mbggenerated Wed Dec 13 20:47:36 CST 2017
     */
    public ClassInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class
     *
     * @mbggenerated Wed Dec 13 20:47:36 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class
     *
     * @mbggenerated Wed Dec 13 20:47:36 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class
     *
     * @mbggenerated Wed Dec 13 20:47:36 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class
     *
     * @mbggenerated Wed Dec 13 20:47:36 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class
     *
     * @mbggenerated Wed Dec 13 20:47:36 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class
     *
     * @mbggenerated Wed Dec 13 20:47:36 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class
     *
     * @mbggenerated Wed Dec 13 20:47:36 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class
     *
     * @mbggenerated Wed Dec 13 20:47:36 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class
     *
     * @mbggenerated Wed Dec 13 20:47:36 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class
     *
     * @mbggenerated Wed Dec 13 20:47:36 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table class
     *
     * @mbggenerated Wed Dec 13 20:47:36 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andClassIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andClassIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andClassIdEqualTo(Integer value) {
            addCriterion("id =", value, "classId");
            return (Criteria) this;
        }

        public Criteria andClassIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "classId");
            return (Criteria) this;
        }

        public Criteria andClassIdGreaterThan(Integer value) {
            addCriterion("id >", value, "classId");
            return (Criteria) this;
        }

        public Criteria andClassIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "classId");
            return (Criteria) this;
        }

        public Criteria andClassIdLessThan(Integer value) {
            addCriterion("id <", value, "classId");
            return (Criteria) this;
        }

        public Criteria andClassIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "classId");
            return (Criteria) this;
        }

        public Criteria andClassIdIn(List<Integer> values) {
            addCriterion("id in", values, "classId");
            return (Criteria) this;
        }

        public Criteria andClassIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "classId");
            return (Criteria) this;
        }

        public Criteria andClassIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "classId");
            return (Criteria) this;
        }

        public Criteria andClassIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "classId");
            return (Criteria) this;
        }

        public Criteria andClassNameIsNull() {
            addCriterion("classname is null");
            return (Criteria) this;
        }

        public Criteria andClassNameIsNotNull() {
            addCriterion("classname is not null");
            return (Criteria) this;
        }

        public Criteria andClassNameEqualTo(String value) {
            addCriterion("classname =", value, "className");
            return (Criteria) this;
        }

        public Criteria andClassNameNotEqualTo(String value) {
            addCriterion("classname <>", value, "className");
            return (Criteria) this;
        }

        public Criteria andClassNameGreaterThan(String value) {
            addCriterion("classname >", value, "className");
            return (Criteria) this;
        }

        public Criteria andClassNameGreaterThanOrEqualTo(String value) {
            addCriterion("classname >=", value, "className");
            return (Criteria) this;
        }

        public Criteria andClassNameLessThan(String value) {
            addCriterion("classname <", value, "className");
            return (Criteria) this;
        }

        public Criteria andClassNameLessThanOrEqualTo(String value) {
            addCriterion("classname <=", value, "className");
            return (Criteria) this;
        }

        public Criteria andClassNameLike(String value) {
            addCriterion("classname like", value, "className");
            return (Criteria) this;
        }

        public Criteria andClassNameNotLike(String value) {
            addCriterion("classname not like", value, "className");
            return (Criteria) this;
        }

        public Criteria andClassNameIn(List<String> values) {
            addCriterion("classname in", values, "className");
            return (Criteria) this;
        }

        public Criteria andClassNameNotIn(List<String> values) {
            addCriterion("classname not in", values, "className");
            return (Criteria) this;
        }

        public Criteria andClassNameBetween(String value1, String value2) {
            addCriterion("classname between", value1, value2, "className");
            return (Criteria) this;
        }

        public Criteria andClassNameNotBetween(String value1, String value2) {
            addCriterion("classname not between", value1, value2, "className");
            return (Criteria) this;
        }

        public Criteria andCreatoridIsNull() {
            addCriterion("creatorid is null");
            return (Criteria) this;
        }

        public Criteria andCreatoridIsNotNull() {
            addCriterion("creatorid is not null");
            return (Criteria) this;
        }

        public Criteria andCreatoridEqualTo(String value) {
            addCriterion("creatorid =", value, "creatorid");
            return (Criteria) this;
        }

        public Criteria andCreatoridNotEqualTo(String value) {
            addCriterion("creatorid <>", value, "creatorid");
            return (Criteria) this;
        }

        public Criteria andCreatoridGreaterThan(String value) {
            addCriterion("creatorid >", value, "creatorid");
            return (Criteria) this;
        }

        public Criteria andCreatoridGreaterThanOrEqualTo(String value) {
            addCriterion("creatorid >=", value, "creatorid");
            return (Criteria) this;
        }

        public Criteria andCreatoridLessThan(String value) {
            addCriterion("creatorid <", value, "creatorid");
            return (Criteria) this;
        }

        public Criteria andCreatoridLessThanOrEqualTo(String value) {
            addCriterion("creatorid <=", value, "creatorid");
            return (Criteria) this;
        }

        public Criteria andCreatoridLike(String value) {
            addCriterion("creatorid like", value, "creatorid");
            return (Criteria) this;
        }

        public Criteria andCreatoridNotLike(String value) {
            addCriterion("creatorid not like", value, "creatorid");
            return (Criteria) this;
        }

        public Criteria andCreatoridIn(List<String> values) {
            addCriterion("creatorid in", values, "creatorid");
            return (Criteria) this;
        }

        public Criteria andCreatoridNotIn(List<String> values) {
            addCriterion("creatorid not in", values, "creatorid");
            return (Criteria) this;
        }

        public Criteria andCreatoridBetween(String value1, String value2) {
            addCriterion("creatorid between", value1, value2, "creatorid");
            return (Criteria) this;
        }

        public Criteria andCreatoridNotBetween(String value1, String value2) {
            addCriterion("creatorid not between", value1, value2, "creatorid");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("cretime is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("cretime is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(String value) {
            addCriterion("cretime =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(String value) {
            addCriterion("cretime <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(String value) {
            addCriterion("cretime >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(String value) {
            addCriterion("cretime >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(String value) {
            addCriterion("cretime <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(String value) {
            addCriterion("cretime <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLike(String value) {
            addCriterion("cretime like", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotLike(String value) {
            addCriterion("cretime not like", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<String> values) {
            addCriterion("cretime in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<String> values) {
            addCriterion("cretime not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(String value1, String value2) {
            addCriterion("cretime between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(String value1, String value2) {
            addCriterion("cretime not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andClassIconIsNull() {
            addCriterion("classicon is null");
            return (Criteria) this;
        }

        public Criteria andClassIconIsNotNull() {
            addCriterion("classicon is not null");
            return (Criteria) this;
        }

        public Criteria andClassIconEqualTo(String value) {
            addCriterion("classicon =", value, "classIcon");
            return (Criteria) this;
        }

        public Criteria andClassIconNotEqualTo(String value) {
            addCriterion("classicon <>", value, "classIcon");
            return (Criteria) this;
        }

        public Criteria andClassIconGreaterThan(String value) {
            addCriterion("classicon >", value, "classIcon");
            return (Criteria) this;
        }

        public Criteria andClassIconGreaterThanOrEqualTo(String value) {
            addCriterion("classicon >=", value, "classIcon");
            return (Criteria) this;
        }

        public Criteria andClassIconLessThan(String value) {
            addCriterion("classicon <", value, "classIcon");
            return (Criteria) this;
        }

        public Criteria andClassIconLessThanOrEqualTo(String value) {
            addCriterion("classicon <=", value, "classIcon");
            return (Criteria) this;
        }

        public Criteria andClassIconLike(String value) {
            addCriterion("classicon like", value, "classIcon");
            return (Criteria) this;
        }

        public Criteria andClassIconNotLike(String value) {
            addCriterion("classicon not like", value, "classIcon");
            return (Criteria) this;
        }

        public Criteria andClassIconIn(List<String> values) {
            addCriterion("classicon in", values, "classIcon");
            return (Criteria) this;
        }

        public Criteria andClassIconNotIn(List<String> values) {
            addCriterion("classicon not in", values, "classIcon");
            return (Criteria) this;
        }

        public Criteria andClassIconBetween(String value1, String value2) {
            addCriterion("classicon between", value1, value2, "classIcon");
            return (Criteria) this;
        }

        public Criteria andClassIconNotBetween(String value1, String value2) {
            addCriterion("classicon not between", value1, value2, "classIcon");
            return (Criteria) this;
        }

        public Criteria andStudentSizeIsNull() {
            addCriterion("ssize is null");
            return (Criteria) this;
        }

        public Criteria andStudentSizeIsNotNull() {
            addCriterion("ssize is not null");
            return (Criteria) this;
        }

        public Criteria andStudentSizeEqualTo(Integer value) {
            addCriterion("ssize =", value, "studentSize");
            return (Criteria) this;
        }

        public Criteria andStudentSizeNotEqualTo(Integer value) {
            addCriterion("ssize <>", value, "studentSize");
            return (Criteria) this;
        }

        public Criteria andStudentSizeGreaterThan(Integer value) {
            addCriterion("ssize >", value, "studentSize");
            return (Criteria) this;
        }

        public Criteria andStudentSizeGreaterThanOrEqualTo(Integer value) {
            addCriterion("ssize >=", value, "studentSize");
            return (Criteria) this;
        }

        public Criteria andStudentSizeLessThan(Integer value) {
            addCriterion("ssize <", value, "studentSize");
            return (Criteria) this;
        }

        public Criteria andStudentSizeLessThanOrEqualTo(Integer value) {
            addCriterion("ssize <=", value, "studentSize");
            return (Criteria) this;
        }

        public Criteria andStudentSizeIn(List<Integer> values) {
            addCriterion("ssize in", values, "studentSize");
            return (Criteria) this;
        }

        public Criteria andStudentSizeNotIn(List<Integer> values) {
            addCriterion("ssize not in", values, "studentSize");
            return (Criteria) this;
        }

        public Criteria andStudentSizeBetween(Integer value1, Integer value2) {
            addCriterion("ssize between", value1, value2, "studentSize");
            return (Criteria) this;
        }

        public Criteria andStudentSizeNotBetween(Integer value1, Integer value2) {
            addCriterion("ssize not between", value1, value2, "studentSize");
            return (Criteria) this;
        }

        public Criteria andTeacherSizeIsNull() {
            addCriterion("tsize is null");
            return (Criteria) this;
        }

        public Criteria andTeacherSizeIsNotNull() {
            addCriterion("tsize is not null");
            return (Criteria) this;
        }

        public Criteria andTeacherSizeEqualTo(Integer value) {
            addCriterion("tsize =", value, "teacherSize");
            return (Criteria) this;
        }

        public Criteria andTeacherSizeNotEqualTo(Integer value) {
            addCriterion("tsize <>", value, "teacherSize");
            return (Criteria) this;
        }

        public Criteria andTeacherSizeGreaterThan(Integer value) {
            addCriterion("tsize >", value, "teacherSize");
            return (Criteria) this;
        }

        public Criteria andTeacherSizeGreaterThanOrEqualTo(Integer value) {
            addCriterion("tsize >=", value, "teacherSize");
            return (Criteria) this;
        }

        public Criteria andTeacherSizeLessThan(Integer value) {
            addCriterion("tsize <", value, "teacherSize");
            return (Criteria) this;
        }

        public Criteria andTeacherSizeLessThanOrEqualTo(Integer value) {
            addCriterion("tsize <=", value, "teacherSize");
            return (Criteria) this;
        }

        public Criteria andTeacherSizeIn(List<Integer> values) {
            addCriterion("tsize in", values, "teacherSize");
            return (Criteria) this;
        }

        public Criteria andTeacherSizeNotIn(List<Integer> values) {
            addCriterion("tsize not in", values, "teacherSize");
            return (Criteria) this;
        }

        public Criteria andTeacherSizeBetween(Integer value1, Integer value2) {
            addCriterion("tsize between", value1, value2, "teacherSize");
            return (Criteria) this;
        }

        public Criteria andTeacherSizeNotBetween(Integer value1, Integer value2) {
            addCriterion("tsize not between", value1, value2, "teacherSize");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table class
     *
     * @mbggenerated do_not_delete_during_merge Wed Dec 13 20:47:36 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table class
     *
     * @mbggenerated Wed Dec 13 20:47:36 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}