package com.wewin.entity;

import org.springframework.stereotype.Component;

@Component
public class ClassInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class.id
     *
     * @mbggenerated Wed Dec 13 20:47:36 CST 2017
     */
    private Integer classId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class.classname
     *
     * @mbggenerated Wed Dec 13 20:47:36 CST 2017
     */
    private String className;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class.creatorid
     *
     * @mbggenerated Wed Dec 13 20:47:36 CST 2017
     */
    private String creatorid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class.cretime
     *
     * @mbggenerated Wed Dec 13 20:47:36 CST 2017
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class.classicon
     *
     * @mbggenerated Wed Dec 13 20:47:36 CST 2017
     */
    private String classIcon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class.ssize
     *
     * @mbggenerated Wed Dec 13 20:47:36 CST 2017
     */
    private Integer studentSize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class.tsize
     *
     * @mbggenerated Wed Dec 13 20:47:36 CST 2017
     */
    private Integer teacherSize;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class.id
     *
     * @return the value of class.id
     *
     * @mbggenerated Wed Dec 13 20:47:36 CST 2017
     */
    public Integer getClassId() {
        return classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class.id
     *
     * @param classId the value for class.id
     *
     * @mbggenerated Wed Dec 13 20:47:36 CST 2017
     */
    public void setClassId(Integer classId) {
        this.classId = classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class.classname
     *
     * @return the value of class.classname
     *
     * @mbggenerated Wed Dec 13 20:47:36 CST 2017
     */
    public String getClassName() {
        return className;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class.classname
     *
     * @param className the value for class.classname
     *
     * @mbggenerated Wed Dec 13 20:47:36 CST 2017
     */
    public void setClassName(String className) {
        this.className = className;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class.creatorid
     *
     * @return the value of class.creatorid
     *
     * @mbggenerated Wed Dec 13 20:47:36 CST 2017
     */
    public String getCreatorid() {
        return creatorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class.creatorid
     *
     * @param creatorid the value for class.creatorid
     *
     * @mbggenerated Wed Dec 13 20:47:36 CST 2017
     */
    public void setCreatorid(String creatorid) {
        this.creatorid = creatorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class.cretime
     *
     * @return the value of class.cretime
     *
     * @mbggenerated Wed Dec 13 20:47:36 CST 2017
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class.cretime
     *
     * @param createTime the value for class.cretime
     *
     * @mbggenerated Wed Dec 13 20:47:36 CST 2017
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class.classicon
     *
     * @return the value of class.classicon
     *
     * @mbggenerated Wed Dec 13 20:47:36 CST 2017
     */
    public String getClassIcon() {
        return classIcon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class.classicon
     *
     * @param classIcon the value for class.classicon
     *
     * @mbggenerated Wed Dec 13 20:47:36 CST 2017
     */
    public void setClassIcon(String classIcon) {
        this.classIcon = classIcon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class.ssize
     *
     * @return the value of class.ssize
     *
     * @mbggenerated Wed Dec 13 20:47:36 CST 2017
     */
    public Integer getStudentSize() {
        return studentSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class.ssize
     *
     * @param studentSize the value for class.ssize
     *
     * @mbggenerated Wed Dec 13 20:47:36 CST 2017
     */
    public void setStudentSize(Integer studentSize) {
        this.studentSize = studentSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class.tsize
     *
     * @return the value of class.tsize
     *
     * @mbggenerated Wed Dec 13 20:47:36 CST 2017
     */
    public Integer getTeacherSize() {
        return teacherSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class.tsize
     *
     * @param teacherSize the value for class.tsize
     *
     * @mbggenerated Wed Dec 13 20:47:36 CST 2017
     */
    public void setTeacherSize(Integer teacherSize) {
        this.teacherSize = teacherSize;
    }
}