package com.wewin.entity;

import org.springframework.stereotype.Component;

@Component
public class GroupInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group.id
     *
     * @mbggenerated Wed Dec 13 22:08:03 CST 2017
     */
    private Integer groupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group.groupname
     *
     * @mbggenerated Wed Dec 13 22:08:03 CST 2017
     */
    private String groupName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group.classid
     *
     * @mbggenerated Wed Dec 13 22:08:03 CST 2017
     */
    private Integer classId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group.memsize
     *
     * @mbggenerated Wed Dec 13 22:08:03 CST 2017
     */
    private Integer memberSize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group.auth
     *
     * @mbggenerated Wed Dec 13 22:08:03 CST 2017
     */
    private Integer groupAuth;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group.id
     *
     * @return the value of group.id
     *
     * @mbggenerated Wed Dec 13 22:08:03 CST 2017
     */
    public Integer getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group.id
     *
     * @param groupId the value for group.id
     *
     * @mbggenerated Wed Dec 13 22:08:03 CST 2017
     */
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group.groupname
     *
     * @return the value of group.groupname
     *
     * @mbggenerated Wed Dec 13 22:08:03 CST 2017
     */
    public String getGroupName() {
        return groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group.groupname
     *
     * @param groupName the value for group.groupname
     *
     * @mbggenerated Wed Dec 13 22:08:03 CST 2017
     */
    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group.classid
     *
     * @return the value of group.classid
     *
     * @mbggenerated Wed Dec 13 22:08:03 CST 2017
     */
    public Integer getClassId() {
        return classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group.classid
     *
     * @param classId the value for group.classid
     *
     * @mbggenerated Wed Dec 13 22:08:03 CST 2017
     */
    public void setClassId(Integer classId) {
        this.classId = classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group.memsize
     *
     * @return the value of group.memsize
     *
     * @mbggenerated Wed Dec 13 22:08:03 CST 2017
     */
    public Integer getMemberSize() {
        return memberSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group.memsize
     *
     * @param memberSize the value for group.memsize
     *
     * @mbggenerated Wed Dec 13 22:08:03 CST 2017
     */
    public void setMemberSize(Integer memberSize) {
        this.memberSize = memberSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group.auth
     *
     * @return the value of group.auth
     *
     * @mbggenerated Wed Dec 13 22:08:03 CST 2017
     */
    public Integer getGroupAuth() {
        return groupAuth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group.auth
     *
     * @param groupAuth the value for group.auth
     *
     * @mbggenerated Wed Dec 13 22:08:03 CST 2017
     */
    public void setGroupAuth(Integer groupAuth) {
        this.groupAuth = groupAuth;
    }
}