package com.wewin.entity;

import java.util.ArrayList;
import java.util.List;

public class HomeWorkExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table homework
     *
     * @mbggenerated Thu Jan 25 13:08:06 GMT+08:00 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table homework
     *
     * @mbggenerated Thu Jan 25 13:08:06 GMT+08:00 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table homework
     *
     * @mbggenerated Thu Jan 25 13:08:06 GMT+08:00 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table homework
     *
     * @mbggenerated Thu Jan 25 13:08:06 GMT+08:00 2018
     */
    public HomeWorkExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table homework
     *
     * @mbggenerated Thu Jan 25 13:08:06 GMT+08:00 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table homework
     *
     * @mbggenerated Thu Jan 25 13:08:06 GMT+08:00 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table homework
     *
     * @mbggenerated Thu Jan 25 13:08:06 GMT+08:00 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table homework
     *
     * @mbggenerated Thu Jan 25 13:08:06 GMT+08:00 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table homework
     *
     * @mbggenerated Thu Jan 25 13:08:06 GMT+08:00 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table homework
     *
     * @mbggenerated Thu Jan 25 13:08:06 GMT+08:00 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table homework
     *
     * @mbggenerated Thu Jan 25 13:08:06 GMT+08:00 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table homework
     *
     * @mbggenerated Thu Jan 25 13:08:06 GMT+08:00 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table homework
     *
     * @mbggenerated Thu Jan 25 13:08:06 GMT+08:00 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table homework
     *
     * @mbggenerated Thu Jan 25 13:08:06 GMT+08:00 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table homework
     *
     * @mbggenerated Thu Jan 25 13:08:06 GMT+08:00 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andHomeworknoIsNull() {
            addCriterion("homeworkno is null");
            return (Criteria) this;
        }

        public Criteria andHomeworknoIsNotNull() {
            addCriterion("homeworkno is not null");
            return (Criteria) this;
        }

        public Criteria andHomeworknoEqualTo(Integer value) {
            addCriterion("homeworkno =", value, "homeworkno");
            return (Criteria) this;
        }

        public Criteria andHomeworknoNotEqualTo(Integer value) {
            addCriterion("homeworkno <>", value, "homeworkno");
            return (Criteria) this;
        }

        public Criteria andHomeworknoGreaterThan(Integer value) {
            addCriterion("homeworkno >", value, "homeworkno");
            return (Criteria) this;
        }

        public Criteria andHomeworknoGreaterThanOrEqualTo(Integer value) {
            addCriterion("homeworkno >=", value, "homeworkno");
            return (Criteria) this;
        }

        public Criteria andHomeworknoLessThan(Integer value) {
            addCriterion("homeworkno <", value, "homeworkno");
            return (Criteria) this;
        }

        public Criteria andHomeworknoLessThanOrEqualTo(Integer value) {
            addCriterion("homeworkno <=", value, "homeworkno");
            return (Criteria) this;
        }

        public Criteria andHomeworknoIn(List<Integer> values) {
            addCriterion("homeworkno in", values, "homeworkno");
            return (Criteria) this;
        }

        public Criteria andHomeworknoNotIn(List<Integer> values) {
            addCriterion("homeworkno not in", values, "homeworkno");
            return (Criteria) this;
        }

        public Criteria andHomeworknoBetween(Integer value1, Integer value2) {
            addCriterion("homeworkno between", value1, value2, "homeworkno");
            return (Criteria) this;
        }

        public Criteria andHomeworknoNotBetween(Integer value1, Integer value2) {
            addCriterion("homeworkno not between", value1, value2, "homeworkno");
            return (Criteria) this;
        }

        public Criteria andPublisherIsNull() {
            addCriterion("publisher is null");
            return (Criteria) this;
        }

        public Criteria andPublisherIsNotNull() {
            addCriterion("publisher is not null");
            return (Criteria) this;
        }

        public Criteria andPublisherEqualTo(String value) {
            addCriterion("publisher =", value, "publisher");
            return (Criteria) this;
        }

        public Criteria andPublisherNotEqualTo(String value) {
            addCriterion("publisher <>", value, "publisher");
            return (Criteria) this;
        }

        public Criteria andPublisherGreaterThan(String value) {
            addCriterion("publisher >", value, "publisher");
            return (Criteria) this;
        }

        public Criteria andPublisherGreaterThanOrEqualTo(String value) {
            addCriterion("publisher >=", value, "publisher");
            return (Criteria) this;
        }

        public Criteria andPublisherLessThan(String value) {
            addCriterion("publisher <", value, "publisher");
            return (Criteria) this;
        }

        public Criteria andPublisherLessThanOrEqualTo(String value) {
            addCriterion("publisher <=", value, "publisher");
            return (Criteria) this;
        }

        public Criteria andPublisherLike(String value) {
            addCriterion("publisher like", value, "publisher");
            return (Criteria) this;
        }

        public Criteria andPublisherNotLike(String value) {
            addCriterion("publisher not like", value, "publisher");
            return (Criteria) this;
        }

        public Criteria andPublisherIn(List<String> values) {
            addCriterion("publisher in", values, "publisher");
            return (Criteria) this;
        }

        public Criteria andPublisherNotIn(List<String> values) {
            addCriterion("publisher not in", values, "publisher");
            return (Criteria) this;
        }

        public Criteria andPublisherBetween(String value1, String value2) {
            addCriterion("publisher between", value1, value2, "publisher");
            return (Criteria) this;
        }

        public Criteria andPublisherNotBetween(String value1, String value2) {
            addCriterion("publisher not between", value1, value2, "publisher");
            return (Criteria) this;
        }

        public Criteria andPublishtimeIsNull() {
            addCriterion("publishtime is null");
            return (Criteria) this;
        }

        public Criteria andPublishtimeIsNotNull() {
            addCriterion("publishtime is not null");
            return (Criteria) this;
        }

        public Criteria andPublishtimeEqualTo(String value) {
            addCriterion("publishtime =", value, "publishtime");
            return (Criteria) this;
        }

        public Criteria andPublishtimeNotEqualTo(String value) {
            addCriterion("publishtime <>", value, "publishtime");
            return (Criteria) this;
        }

        public Criteria andPublishtimeGreaterThan(String value) {
            addCriterion("publishtime >", value, "publishtime");
            return (Criteria) this;
        }

        public Criteria andPublishtimeGreaterThanOrEqualTo(String value) {
            addCriterion("publishtime >=", value, "publishtime");
            return (Criteria) this;
        }

        public Criteria andPublishtimeLessThan(String value) {
            addCriterion("publishtime <", value, "publishtime");
            return (Criteria) this;
        }

        public Criteria andPublishtimeLessThanOrEqualTo(String value) {
            addCriterion("publishtime <=", value, "publishtime");
            return (Criteria) this;
        }

        public Criteria andPublishtimeLike(String value) {
            addCriterion("publishtime like", value, "publishtime");
            return (Criteria) this;
        }

        public Criteria andPublishtimeNotLike(String value) {
            addCriterion("publishtime not like", value, "publishtime");
            return (Criteria) this;
        }

        public Criteria andPublishtimeIn(List<String> values) {
            addCriterion("publishtime in", values, "publishtime");
            return (Criteria) this;
        }

        public Criteria andPublishtimeNotIn(List<String> values) {
            addCriterion("publishtime not in", values, "publishtime");
            return (Criteria) this;
        }

        public Criteria andPublishtimeBetween(String value1, String value2) {
            addCriterion("publishtime between", value1, value2, "publishtime");
            return (Criteria) this;
        }

        public Criteria andPublishtimeNotBetween(String value1, String value2) {
            addCriterion("publishtime not between", value1, value2, "publishtime");
            return (Criteria) this;
        }

        public Criteria andContentIsNull() {
            addCriterion("content is null");
            return (Criteria) this;
        }

        public Criteria andContentIsNotNull() {
            addCriterion("content is not null");
            return (Criteria) this;
        }

        public Criteria andContentEqualTo(String value) {
            addCriterion("content =", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotEqualTo(String value) {
            addCriterion("content <>", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentGreaterThan(String value) {
            addCriterion("content >", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentGreaterThanOrEqualTo(String value) {
            addCriterion("content >=", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentLessThan(String value) {
            addCriterion("content <", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentLessThanOrEqualTo(String value) {
            addCriterion("content <=", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentLike(String value) {
            addCriterion("content like", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotLike(String value) {
            addCriterion("content not like", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentIn(List<String> values) {
            addCriterion("content in", values, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotIn(List<String> values) {
            addCriterion("content not in", values, "content");
            return (Criteria) this;
        }

        public Criteria andContentBetween(String value1, String value2) {
            addCriterion("content between", value1, value2, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotBetween(String value1, String value2) {
            addCriterion("content not between", value1, value2, "content");
            return (Criteria) this;
        }

        public Criteria andTargetclassIsNull() {
            addCriterion("targetclass is null");
            return (Criteria) this;
        }

        public Criteria andTargetclassIsNotNull() {
            addCriterion("targetclass is not null");
            return (Criteria) this;
        }

        public Criteria andTargetclassEqualTo(String value) {
            addCriterion("targetclass =", value, "targetclass");
            return (Criteria) this;
        }

        public Criteria andTargetclassNotEqualTo(String value) {
            addCriterion("targetclass <>", value, "targetclass");
            return (Criteria) this;
        }

        public Criteria andTargetclassGreaterThan(String value) {
            addCriterion("targetclass >", value, "targetclass");
            return (Criteria) this;
        }

        public Criteria andTargetclassGreaterThanOrEqualTo(String value) {
            addCriterion("targetclass >=", value, "targetclass");
            return (Criteria) this;
        }

        public Criteria andTargetclassLessThan(String value) {
            addCriterion("targetclass <", value, "targetclass");
            return (Criteria) this;
        }

        public Criteria andTargetclassLessThanOrEqualTo(String value) {
            addCriterion("targetclass <=", value, "targetclass");
            return (Criteria) this;
        }

        public Criteria andTargetclassLike(String value) {
            addCriterion("targetclass like", value, "targetclass");
            return (Criteria) this;
        }

        public Criteria andTargetclassNotLike(String value) {
            addCriterion("targetclass not like", value, "targetclass");
            return (Criteria) this;
        }

        public Criteria andTargetclassIn(List<String> values) {
            addCriterion("targetclass in", values, "targetclass");
            return (Criteria) this;
        }

        public Criteria andTargetclassNotIn(List<String> values) {
            addCriterion("targetclass not in", values, "targetclass");
            return (Criteria) this;
        }

        public Criteria andTargetclassBetween(String value1, String value2) {
            addCriterion("targetclass between", value1, value2, "targetclass");
            return (Criteria) this;
        }

        public Criteria andTargetclassNotBetween(String value1, String value2) {
            addCriterion("targetclass not between", value1, value2, "targetclass");
            return (Criteria) this;
        }

        public Criteria andOpenidIsNull() {
            addCriterion("openid is null");
            return (Criteria) this;
        }

        public Criteria andOpenidIsNotNull() {
            addCriterion("openid is not null");
            return (Criteria) this;
        }

        public Criteria andOpenidEqualTo(String value) {
            addCriterion("openid =", value, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidNotEqualTo(String value) {
            addCriterion("openid <>", value, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidGreaterThan(String value) {
            addCriterion("openid >", value, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidGreaterThanOrEqualTo(String value) {
            addCriterion("openid >=", value, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidLessThan(String value) {
            addCriterion("openid <", value, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidLessThanOrEqualTo(String value) {
            addCriterion("openid <=", value, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidLike(String value) {
            addCriterion("openid like", value, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidNotLike(String value) {
            addCriterion("openid not like", value, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidIn(List<String> values) {
            addCriterion("openid in", values, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidNotIn(List<String> values) {
            addCriterion("openid not in", values, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidBetween(String value1, String value2) {
            addCriterion("openid between", value1, value2, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidNotBetween(String value1, String value2) {
            addCriterion("openid not between", value1, value2, "openid");
            return (Criteria) this;
        }

        public Criteria andDeadlineIsNull() {
            addCriterion("deadline is null");
            return (Criteria) this;
        }

        public Criteria andDeadlineIsNotNull() {
            addCriterion("deadline is not null");
            return (Criteria) this;
        }

        public Criteria andDeadlineEqualTo(String value) {
            addCriterion("deadline =", value, "deadline");
            return (Criteria) this;
        }

        public Criteria andDeadlineNotEqualTo(String value) {
            addCriterion("deadline <>", value, "deadline");
            return (Criteria) this;
        }

        public Criteria andDeadlineGreaterThan(String value) {
            addCriterion("deadline >", value, "deadline");
            return (Criteria) this;
        }

        public Criteria andDeadlineGreaterThanOrEqualTo(String value) {
            addCriterion("deadline >=", value, "deadline");
            return (Criteria) this;
        }

        public Criteria andDeadlineLessThan(String value) {
            addCriterion("deadline <", value, "deadline");
            return (Criteria) this;
        }

        public Criteria andDeadlineLessThanOrEqualTo(String value) {
            addCriterion("deadline <=", value, "deadline");
            return (Criteria) this;
        }

        public Criteria andDeadlineLike(String value) {
            addCriterion("deadline like", value, "deadline");
            return (Criteria) this;
        }

        public Criteria andDeadlineNotLike(String value) {
            addCriterion("deadline not like", value, "deadline");
            return (Criteria) this;
        }

        public Criteria andDeadlineIn(List<String> values) {
            addCriterion("deadline in", values, "deadline");
            return (Criteria) this;
        }

        public Criteria andDeadlineNotIn(List<String> values) {
            addCriterion("deadline not in", values, "deadline");
            return (Criteria) this;
        }

        public Criteria andDeadlineBetween(String value1, String value2) {
            addCriterion("deadline between", value1, value2, "deadline");
            return (Criteria) this;
        }

        public Criteria andDeadlineNotBetween(String value1, String value2) {
            addCriterion("deadline not between", value1, value2, "deadline");
            return (Criteria) this;
        }

        public Criteria andUrlIsNull() {
            addCriterion("url is null");
            return (Criteria) this;
        }

        public Criteria andUrlIsNotNull() {
            addCriterion("url is not null");
            return (Criteria) this;
        }

        public Criteria andUrlEqualTo(String value) {
            addCriterion("url =", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotEqualTo(String value) {
            addCriterion("url <>", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlGreaterThan(String value) {
            addCriterion("url >", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlGreaterThanOrEqualTo(String value) {
            addCriterion("url >=", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlLessThan(String value) {
            addCriterion("url <", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlLessThanOrEqualTo(String value) {
            addCriterion("url <=", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlLike(String value) {
            addCriterion("url like", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotLike(String value) {
            addCriterion("url not like", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlIn(List<String> values) {
            addCriterion("url in", values, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotIn(List<String> values) {
            addCriterion("url not in", values, "url");
            return (Criteria) this;
        }

        public Criteria andUrlBetween(String value1, String value2) {
            addCriterion("url between", value1, value2, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotBetween(String value1, String value2) {
            addCriterion("url not between", value1, value2, "url");
            return (Criteria) this;
        }

        public Criteria andTitleIsNull() {
            addCriterion("title is null");
            return (Criteria) this;
        }

        public Criteria andTitleIsNotNull() {
            addCriterion("title is not null");
            return (Criteria) this;
        }

        public Criteria andTitleEqualTo(String value) {
            addCriterion("title =", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotEqualTo(String value) {
            addCriterion("title <>", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThan(String value) {
            addCriterion("title >", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThanOrEqualTo(String value) {
            addCriterion("title >=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThan(String value) {
            addCriterion("title <", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThanOrEqualTo(String value) {
            addCriterion("title <=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLike(String value) {
            addCriterion("title like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotLike(String value) {
            addCriterion("title not like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleIn(List<String> values) {
            addCriterion("title in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotIn(List<String> values) {
            addCriterion("title not in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleBetween(String value1, String value2) {
            addCriterion("title between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotBetween(String value1, String value2) {
            addCriterion("title not between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andHomeworkcolIsNull() {
            addCriterion("homeworkcol is null");
            return (Criteria) this;
        }

        public Criteria andHomeworkcolIsNotNull() {
            addCriterion("homeworkcol is not null");
            return (Criteria) this;
        }

        public Criteria andHomeworkcolEqualTo(String value) {
            addCriterion("homeworkcol =", value, "homeworkcol");
            return (Criteria) this;
        }

        public Criteria andHomeworkcolNotEqualTo(String value) {
            addCriterion("homeworkcol <>", value, "homeworkcol");
            return (Criteria) this;
        }

        public Criteria andHomeworkcolGreaterThan(String value) {
            addCriterion("homeworkcol >", value, "homeworkcol");
            return (Criteria) this;
        }

        public Criteria andHomeworkcolGreaterThanOrEqualTo(String value) {
            addCriterion("homeworkcol >=", value, "homeworkcol");
            return (Criteria) this;
        }

        public Criteria andHomeworkcolLessThan(String value) {
            addCriterion("homeworkcol <", value, "homeworkcol");
            return (Criteria) this;
        }

        public Criteria andHomeworkcolLessThanOrEqualTo(String value) {
            addCriterion("homeworkcol <=", value, "homeworkcol");
            return (Criteria) this;
        }

        public Criteria andHomeworkcolLike(String value) {
            addCriterion("homeworkcol like", value, "homeworkcol");
            return (Criteria) this;
        }

        public Criteria andHomeworkcolNotLike(String value) {
            addCriterion("homeworkcol not like", value, "homeworkcol");
            return (Criteria) this;
        }

        public Criteria andHomeworkcolIn(List<String> values) {
            addCriterion("homeworkcol in", values, "homeworkcol");
            return (Criteria) this;
        }

        public Criteria andHomeworkcolNotIn(List<String> values) {
            addCriterion("homeworkcol not in", values, "homeworkcol");
            return (Criteria) this;
        }

        public Criteria andHomeworkcolBetween(String value1, String value2) {
            addCriterion("homeworkcol between", value1, value2, "homeworkcol");
            return (Criteria) this;
        }

        public Criteria andHomeworkcolNotBetween(String value1, String value2) {
            addCriterion("homeworkcol not between", value1, value2, "homeworkcol");
            return (Criteria) this;
        }

        public Criteria andHomeworkcol1IsNull() {
            addCriterion("homeworkcol1 is null");
            return (Criteria) this;
        }

        public Criteria andHomeworkcol1IsNotNull() {
            addCriterion("homeworkcol1 is not null");
            return (Criteria) this;
        }

        public Criteria andHomeworkcol1EqualTo(String value) {
            addCriterion("homeworkcol1 =", value, "homeworkcol1");
            return (Criteria) this;
        }

        public Criteria andHomeworkcol1NotEqualTo(String value) {
            addCriterion("homeworkcol1 <>", value, "homeworkcol1");
            return (Criteria) this;
        }

        public Criteria andHomeworkcol1GreaterThan(String value) {
            addCriterion("homeworkcol1 >", value, "homeworkcol1");
            return (Criteria) this;
        }

        public Criteria andHomeworkcol1GreaterThanOrEqualTo(String value) {
            addCriterion("homeworkcol1 >=", value, "homeworkcol1");
            return (Criteria) this;
        }

        public Criteria andHomeworkcol1LessThan(String value) {
            addCriterion("homeworkcol1 <", value, "homeworkcol1");
            return (Criteria) this;
        }

        public Criteria andHomeworkcol1LessThanOrEqualTo(String value) {
            addCriterion("homeworkcol1 <=", value, "homeworkcol1");
            return (Criteria) this;
        }

        public Criteria andHomeworkcol1Like(String value) {
            addCriterion("homeworkcol1 like", value, "homeworkcol1");
            return (Criteria) this;
        }

        public Criteria andHomeworkcol1NotLike(String value) {
            addCriterion("homeworkcol1 not like", value, "homeworkcol1");
            return (Criteria) this;
        }

        public Criteria andHomeworkcol1In(List<String> values) {
            addCriterion("homeworkcol1 in", values, "homeworkcol1");
            return (Criteria) this;
        }

        public Criteria andHomeworkcol1NotIn(List<String> values) {
            addCriterion("homeworkcol1 not in", values, "homeworkcol1");
            return (Criteria) this;
        }

        public Criteria andHomeworkcol1Between(String value1, String value2) {
            addCriterion("homeworkcol1 between", value1, value2, "homeworkcol1");
            return (Criteria) this;
        }

        public Criteria andHomeworkcol1NotBetween(String value1, String value2) {
            addCriterion("homeworkcol1 not between", value1, value2, "homeworkcol1");
            return (Criteria) this;
        }

        public Criteria andHomeworkcol2IsNull() {
            addCriterion("homeworkcol2 is null");
            return (Criteria) this;
        }

        public Criteria andHomeworkcol2IsNotNull() {
            addCriterion("homeworkcol2 is not null");
            return (Criteria) this;
        }

        public Criteria andHomeworkcol2EqualTo(String value) {
            addCriterion("homeworkcol2 =", value, "homeworkcol2");
            return (Criteria) this;
        }

        public Criteria andHomeworkcol2NotEqualTo(String value) {
            addCriterion("homeworkcol2 <>", value, "homeworkcol2");
            return (Criteria) this;
        }

        public Criteria andHomeworkcol2GreaterThan(String value) {
            addCriterion("homeworkcol2 >", value, "homeworkcol2");
            return (Criteria) this;
        }

        public Criteria andHomeworkcol2GreaterThanOrEqualTo(String value) {
            addCriterion("homeworkcol2 >=", value, "homeworkcol2");
            return (Criteria) this;
        }

        public Criteria andHomeworkcol2LessThan(String value) {
            addCriterion("homeworkcol2 <", value, "homeworkcol2");
            return (Criteria) this;
        }

        public Criteria andHomeworkcol2LessThanOrEqualTo(String value) {
            addCriterion("homeworkcol2 <=", value, "homeworkcol2");
            return (Criteria) this;
        }

        public Criteria andHomeworkcol2Like(String value) {
            addCriterion("homeworkcol2 like", value, "homeworkcol2");
            return (Criteria) this;
        }

        public Criteria andHomeworkcol2NotLike(String value) {
            addCriterion("homeworkcol2 not like", value, "homeworkcol2");
            return (Criteria) this;
        }

        public Criteria andHomeworkcol2In(List<String> values) {
            addCriterion("homeworkcol2 in", values, "homeworkcol2");
            return (Criteria) this;
        }

        public Criteria andHomeworkcol2NotIn(List<String> values) {
            addCriterion("homeworkcol2 not in", values, "homeworkcol2");
            return (Criteria) this;
        }

        public Criteria andHomeworkcol2Between(String value1, String value2) {
            addCriterion("homeworkcol2 between", value1, value2, "homeworkcol2");
            return (Criteria) this;
        }

        public Criteria andHomeworkcol2NotBetween(String value1, String value2) {
            addCriterion("homeworkcol2 not between", value1, value2, "homeworkcol2");
            return (Criteria) this;
        }

        public Criteria andHomeworkcol3IsNull() {
            addCriterion("homeworkcol3 is null");
            return (Criteria) this;
        }

        public Criteria andHomeworkcol3IsNotNull() {
            addCriterion("homeworkcol3 is not null");
            return (Criteria) this;
        }

        public Criteria andHomeworkcol3EqualTo(String value) {
            addCriterion("homeworkcol3 =", value, "homeworkcol3");
            return (Criteria) this;
        }

        public Criteria andHomeworkcol3NotEqualTo(String value) {
            addCriterion("homeworkcol3 <>", value, "homeworkcol3");
            return (Criteria) this;
        }

        public Criteria andHomeworkcol3GreaterThan(String value) {
            addCriterion("homeworkcol3 >", value, "homeworkcol3");
            return (Criteria) this;
        }

        public Criteria andHomeworkcol3GreaterThanOrEqualTo(String value) {
            addCriterion("homeworkcol3 >=", value, "homeworkcol3");
            return (Criteria) this;
        }

        public Criteria andHomeworkcol3LessThan(String value) {
            addCriterion("homeworkcol3 <", value, "homeworkcol3");
            return (Criteria) this;
        }

        public Criteria andHomeworkcol3LessThanOrEqualTo(String value) {
            addCriterion("homeworkcol3 <=", value, "homeworkcol3");
            return (Criteria) this;
        }

        public Criteria andHomeworkcol3Like(String value) {
            addCriterion("homeworkcol3 like", value, "homeworkcol3");
            return (Criteria) this;
        }

        public Criteria andHomeworkcol3NotLike(String value) {
            addCriterion("homeworkcol3 not like", value, "homeworkcol3");
            return (Criteria) this;
        }

        public Criteria andHomeworkcol3In(List<String> values) {
            addCriterion("homeworkcol3 in", values, "homeworkcol3");
            return (Criteria) this;
        }

        public Criteria andHomeworkcol3NotIn(List<String> values) {
            addCriterion("homeworkcol3 not in", values, "homeworkcol3");
            return (Criteria) this;
        }

        public Criteria andHomeworkcol3Between(String value1, String value2) {
            addCriterion("homeworkcol3 between", value1, value2, "homeworkcol3");
            return (Criteria) this;
        }

        public Criteria andHomeworkcol3NotBetween(String value1, String value2) {
            addCriterion("homeworkcol3 not between", value1, value2, "homeworkcol3");
            return (Criteria) this;
        }

        public Criteria andHomeworkcol4IsNull() {
            addCriterion("homeworkcol4 is null");
            return (Criteria) this;
        }

        public Criteria andHomeworkcol4IsNotNull() {
            addCriterion("homeworkcol4 is not null");
            return (Criteria) this;
        }

        public Criteria andHomeworkcol4EqualTo(String value) {
            addCriterion("homeworkcol4 =", value, "homeworkcol4");
            return (Criteria) this;
        }

        public Criteria andHomeworkcol4NotEqualTo(String value) {
            addCriterion("homeworkcol4 <>", value, "homeworkcol4");
            return (Criteria) this;
        }

        public Criteria andHomeworkcol4GreaterThan(String value) {
            addCriterion("homeworkcol4 >", value, "homeworkcol4");
            return (Criteria) this;
        }

        public Criteria andHomeworkcol4GreaterThanOrEqualTo(String value) {
            addCriterion("homeworkcol4 >=", value, "homeworkcol4");
            return (Criteria) this;
        }

        public Criteria andHomeworkcol4LessThan(String value) {
            addCriterion("homeworkcol4 <", value, "homeworkcol4");
            return (Criteria) this;
        }

        public Criteria andHomeworkcol4LessThanOrEqualTo(String value) {
            addCriterion("homeworkcol4 <=", value, "homeworkcol4");
            return (Criteria) this;
        }

        public Criteria andHomeworkcol4Like(String value) {
            addCriterion("homeworkcol4 like", value, "homeworkcol4");
            return (Criteria) this;
        }

        public Criteria andHomeworkcol4NotLike(String value) {
            addCriterion("homeworkcol4 not like", value, "homeworkcol4");
            return (Criteria) this;
        }

        public Criteria andHomeworkcol4In(List<String> values) {
            addCriterion("homeworkcol4 in", values, "homeworkcol4");
            return (Criteria) this;
        }

        public Criteria andHomeworkcol4NotIn(List<String> values) {
            addCriterion("homeworkcol4 not in", values, "homeworkcol4");
            return (Criteria) this;
        }

        public Criteria andHomeworkcol4Between(String value1, String value2) {
            addCriterion("homeworkcol4 between", value1, value2, "homeworkcol4");
            return (Criteria) this;
        }

        public Criteria andHomeworkcol4NotBetween(String value1, String value2) {
            addCriterion("homeworkcol4 not between", value1, value2, "homeworkcol4");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table homework
     *
     * @mbggenerated do_not_delete_during_merge Thu Jan 25 13:08:06 GMT+08:00 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table homework
     *
     * @mbggenerated Thu Jan 25 13:08:06 GMT+08:00 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}