package com.wewin.entity;

import org.springframework.stereotype.Component;

@Component
public class HomeWork {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column homework.homeworkno
     *
     * @mbggenerated Thu Jan 25 13:08:06 GMT+08:00 2018
     */
    private Integer homeworkno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column homework.publisher
     *
     * @mbggenerated Thu Jan 25 13:08:06 GMT+08:00 2018
     */
    private String publisher;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column homework.publishtime
     *
     * @mbggenerated Thu Jan 25 13:08:06 GMT+08:00 2018
     */
    private String publishtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column homework.content
     *
     * @mbggenerated Thu Jan 25 13:08:06 GMT+08:00 2018
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column homework.targetclass
     *
     * @mbggenerated Thu Jan 25 13:08:06 GMT+08:00 2018
     */
    private String targetclass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column homework.openid
     *
     * @mbggenerated Thu Jan 25 13:08:06 GMT+08:00 2018
     */
    private String openid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column homework.deadline
     *
     * @mbggenerated Thu Jan 25 13:08:06 GMT+08:00 2018
     */
    private String deadline;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column homework.url
     *
     * @mbggenerated Thu Jan 25 13:08:06 GMT+08:00 2018
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column homework.title
     *
     * @mbggenerated Thu Jan 25 13:08:06 GMT+08:00 2018
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column homework.homeworkcol
     *
     * @mbggenerated Thu Jan 25 13:08:06 GMT+08:00 2018
     */
    private String homeworkcol;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column homework.homeworkcol1
     *
     * @mbggenerated Thu Jan 25 13:08:06 GMT+08:00 2018
     */
    private String homeworkcol1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column homework.homeworkcol2
     *
     * @mbggenerated Thu Jan 25 13:08:06 GMT+08:00 2018
     */
    private String homeworkcol2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column homework.homeworkcol3
     *
     * @mbggenerated Thu Jan 25 13:08:06 GMT+08:00 2018
     */
    private String homeworkcol3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column homework.homeworkcol4
     *
     * @mbggenerated Thu Jan 25 13:08:06 GMT+08:00 2018
     */
    private String homeworkcol4;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column homework.homeworkno
     *
     * @return the value of homework.homeworkno
     *
     * @mbggenerated Thu Jan 25 13:08:06 GMT+08:00 2018
     */
    public Integer getHomeworkno() {
        return homeworkno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column homework.homeworkno
     *
     * @param homeworkno the value for homework.homeworkno
     *
     * @mbggenerated Thu Jan 25 13:08:06 GMT+08:00 2018
     */
    public void setHomeworkno(Integer homeworkno) {
        this.homeworkno = homeworkno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column homework.publisher
     *
     * @return the value of homework.publisher
     *
     * @mbggenerated Thu Jan 25 13:08:06 GMT+08:00 2018
     */
    public String getPublisher() {
        return publisher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column homework.publisher
     *
     * @param publisher the value for homework.publisher
     *
     * @mbggenerated Thu Jan 25 13:08:06 GMT+08:00 2018
     */
    public void setPublisher(String publisher) {
        this.publisher = publisher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column homework.publishtime
     *
     * @return the value of homework.publishtime
     *
     * @mbggenerated Thu Jan 25 13:08:06 GMT+08:00 2018
     */
    public String getPublishtime() {
        return publishtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column homework.publishtime
     *
     * @param publishtime the value for homework.publishtime
     *
     * @mbggenerated Thu Jan 25 13:08:06 GMT+08:00 2018
     */
    public void setPublishtime(String publishtime) {
        this.publishtime = publishtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column homework.content
     *
     * @return the value of homework.content
     *
     * @mbggenerated Thu Jan 25 13:08:06 GMT+08:00 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column homework.content
     *
     * @param content the value for homework.content
     *
     * @mbggenerated Thu Jan 25 13:08:06 GMT+08:00 2018
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column homework.targetclass
     *
     * @return the value of homework.targetclass
     *
     * @mbggenerated Thu Jan 25 13:08:06 GMT+08:00 2018
     */
    public String getTargetclass() {
        return targetclass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column homework.targetclass
     *
     * @param targetclass the value for homework.targetclass
     *
     * @mbggenerated Thu Jan 25 13:08:06 GMT+08:00 2018
     */
    public void setTargetclass(String targetclass) {
        this.targetclass = targetclass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column homework.openid
     *
     * @return the value of homework.openid
     *
     * @mbggenerated Thu Jan 25 13:08:06 GMT+08:00 2018
     */
    public String getOpenid() {
        return openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column homework.openid
     *
     * @param openid the value for homework.openid
     *
     * @mbggenerated Thu Jan 25 13:08:06 GMT+08:00 2018
     */
    public void setOpenid(String openid) {
        this.openid = openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column homework.deadline
     *
     * @return the value of homework.deadline
     *
     * @mbggenerated Thu Jan 25 13:08:06 GMT+08:00 2018
     */
    public String getDeadline() {
        return deadline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column homework.deadline
     *
     * @param deadline the value for homework.deadline
     *
     * @mbggenerated Thu Jan 25 13:08:06 GMT+08:00 2018
     */
    public void setDeadline(String deadline) {
        this.deadline = deadline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column homework.url
     *
     * @return the value of homework.url
     *
     * @mbggenerated Thu Jan 25 13:08:06 GMT+08:00 2018
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column homework.url
     *
     * @param url the value for homework.url
     *
     * @mbggenerated Thu Jan 25 13:08:06 GMT+08:00 2018
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column homework.title
     *
     * @return the value of homework.title
     *
     * @mbggenerated Thu Jan 25 13:08:06 GMT+08:00 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column homework.title
     *
     * @param title the value for homework.title
     *
     * @mbggenerated Thu Jan 25 13:08:06 GMT+08:00 2018
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column homework.homeworkcol
     *
     * @return the value of homework.homeworkcol
     *
     * @mbggenerated Thu Jan 25 13:08:06 GMT+08:00 2018
     */
    public String getHomeworkcol() {
        return homeworkcol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column homework.homeworkcol
     *
     * @param homeworkcol the value for homework.homeworkcol
     *
     * @mbggenerated Thu Jan 25 13:08:06 GMT+08:00 2018
     */
    public void setHomeworkcol(String homeworkcol) {
        this.homeworkcol = homeworkcol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column homework.homeworkcol1
     *
     * @return the value of homework.homeworkcol1
     *
     * @mbggenerated Thu Jan 25 13:08:06 GMT+08:00 2018
     */
    public String getHomeworkcol1() {
        return homeworkcol1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column homework.homeworkcol1
     *
     * @param homeworkcol1 the value for homework.homeworkcol1
     *
     * @mbggenerated Thu Jan 25 13:08:06 GMT+08:00 2018
     */
    public void setHomeworkcol1(String homeworkcol1) {
        this.homeworkcol1 = homeworkcol1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column homework.homeworkcol2
     *
     * @return the value of homework.homeworkcol2
     *
     * @mbggenerated Thu Jan 25 13:08:06 GMT+08:00 2018
     */
    public String getHomeworkcol2() {
        return homeworkcol2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column homework.homeworkcol2
     *
     * @param homeworkcol2 the value for homework.homeworkcol2
     *
     * @mbggenerated Thu Jan 25 13:08:06 GMT+08:00 2018
     */
    public void setHomeworkcol2(String homeworkcol2) {
        this.homeworkcol2 = homeworkcol2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column homework.homeworkcol3
     *
     * @return the value of homework.homeworkcol3
     *
     * @mbggenerated Thu Jan 25 13:08:06 GMT+08:00 2018
     */
    public String getHomeworkcol3() {
        return homeworkcol3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column homework.homeworkcol3
     *
     * @param homeworkcol3 the value for homework.homeworkcol3
     *
     * @mbggenerated Thu Jan 25 13:08:06 GMT+08:00 2018
     */
    public void setHomeworkcol3(String homeworkcol3) {
        this.homeworkcol3 = homeworkcol3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column homework.homeworkcol4
     *
     * @return the value of homework.homeworkcol4
     *
     * @mbggenerated Thu Jan 25 13:08:06 GMT+08:00 2018
     */
    public String getHomeworkcol4() {
        return homeworkcol4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column homework.homeworkcol4
     *
     * @param homeworkcol4 the value for homework.homeworkcol4
     *
     * @mbggenerated Thu Jan 25 13:08:06 GMT+08:00 2018
     */
    public void setHomeworkcol4(String homeworkcol4) {
        this.homeworkcol4 = homeworkcol4;
    }
}