package com.wewin.entity;

import org.springframework.stereotype.Component;

@Component
public class Notice {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.id
     *
     * @mbggenerated Wed Jan 24 13:41:17 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.publisher
     *
     * @mbggenerated Wed Jan 24 13:41:17 CST 2018
     */
    private String publisher;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.publishtime
     *
     * @mbggenerated Wed Jan 24 13:41:17 CST 2018
     */
    private String publishtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.content
     *
     * @mbggenerated Wed Jan 24 13:41:17 CST 2018
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.targetclass
     *
     * @mbggenerated Wed Jan 24 13:41:17 CST 2018
     */
    private Integer targetclass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.noticeno
     *
     * @mbggenerated Wed Jan 24 13:41:17 CST 2018
     */
    private Integer noticeno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.pic_url
     *
     * @mbggenerated Wed Jan 24 13:41:17 CST 2018
     */
    private String picUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.mov_url
     *
     * @mbggenerated Wed Jan 24 13:41:17 CST 2018
     */
    private String movUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.file_url
     *
     * @mbggenerated Wed Jan 24 13:41:17 CST 2018
     */
    private String fileUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.title
     *
     * @mbggenerated Wed Jan 24 13:41:17 CST 2018
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.read_num
     *
     * @mbggenerated Wed Jan 24 13:41:17 CST 2018
     */
    private Integer readNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.endtime
     *
     * @mbggenerated Wed Jan 24 13:41:17 CST 2018
     */
    private String endtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.redu1
     *
     * @mbggenerated Wed Jan 24 13:41:17 CST 2018
     */
    private String redu1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.redu2
     *
     * @mbggenerated Wed Jan 24 13:41:17 CST 2018
     */
    private String redu2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.redu3
     *
     * @mbggenerated Wed Jan 24 13:41:17 CST 2018
     */
    private String redu3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.redu4
     *
     * @mbggenerated Wed Jan 24 13:41:17 CST 2018
     */
    private String redu4;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.id
     *
     * @return the value of notice.id
     *
     * @mbggenerated Wed Jan 24 13:41:17 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.id
     *
     * @param id the value for notice.id
     *
     * @mbggenerated Wed Jan 24 13:41:17 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.publisher
     *
     * @return the value of notice.publisher
     *
     * @mbggenerated Wed Jan 24 13:41:17 CST 2018
     */
    public String getPublisher() {
        return publisher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.publisher
     *
     * @param publisher the value for notice.publisher
     *
     * @mbggenerated Wed Jan 24 13:41:17 CST 2018
     */
    public void setPublisher(String publisher) {
        this.publisher = publisher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.publishtime
     *
     * @return the value of notice.publishtime
     *
     * @mbggenerated Wed Jan 24 13:41:17 CST 2018
     */
    public String getPublishtime() {
        return publishtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.publishtime
     *
     * @param publishtime the value for notice.publishtime
     *
     * @mbggenerated Wed Jan 24 13:41:17 CST 2018
     */
    public void setPublishtime(String publishtime) {
        this.publishtime = publishtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.content
     *
     * @return the value of notice.content
     *
     * @mbggenerated Wed Jan 24 13:41:17 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.content
     *
     * @param content the value for notice.content
     *
     * @mbggenerated Wed Jan 24 13:41:17 CST 2018
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.targetclass
     *
     * @return the value of notice.targetclass
     *
     * @mbggenerated Wed Jan 24 13:41:17 CST 2018
     */
    public Integer getTargetclass() {
        return targetclass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.targetclass
     *
     * @param targetclass the value for notice.targetclass
     *
     * @mbggenerated Wed Jan 24 13:41:17 CST 2018
     */
    public void setTargetclass(Integer targetclass) {
        this.targetclass = targetclass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.noticeno
     *
     * @return the value of notice.noticeno
     *
     * @mbggenerated Wed Jan 24 13:41:17 CST 2018
     */
    public Integer getNoticeno() {
        return noticeno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.noticeno
     *
     * @param noticeno the value for notice.noticeno
     *
     * @mbggenerated Wed Jan 24 13:41:17 CST 2018
     */
    public void setNoticeno(Integer noticeno) {
        this.noticeno = noticeno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.pic_url
     *
     * @return the value of notice.pic_url
     *
     * @mbggenerated Wed Jan 24 13:41:17 CST 2018
     */
    public String getPicUrl() {
        return picUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.pic_url
     *
     * @param picUrl the value for notice.pic_url
     *
     * @mbggenerated Wed Jan 24 13:41:17 CST 2018
     */
    public void setPicUrl(String picUrl) {
        this.picUrl = picUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.mov_url
     *
     * @return the value of notice.mov_url
     *
     * @mbggenerated Wed Jan 24 13:41:17 CST 2018
     */
    public String getMovUrl() {
        return movUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.mov_url
     *
     * @param movUrl the value for notice.mov_url
     *
     * @mbggenerated Wed Jan 24 13:41:17 CST 2018
     */
    public void setMovUrl(String movUrl) {
        this.movUrl = movUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.file_url
     *
     * @return the value of notice.file_url
     *
     * @mbggenerated Wed Jan 24 13:41:17 CST 2018
     */
    public String getFileUrl() {
        return fileUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.file_url
     *
     * @param fileUrl the value for notice.file_url
     *
     * @mbggenerated Wed Jan 24 13:41:17 CST 2018
     */
    public void setFileUrl(String fileUrl) {
        this.fileUrl = fileUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.title
     *
     * @return the value of notice.title
     *
     * @mbggenerated Wed Jan 24 13:41:17 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.title
     *
     * @param title the value for notice.title
     *
     * @mbggenerated Wed Jan 24 13:41:17 CST 2018
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.read_num
     *
     * @return the value of notice.read_num
     *
     * @mbggenerated Wed Jan 24 13:41:17 CST 2018
     */
    public Integer getReadNum() {
        return readNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.read_num
     *
     * @param readNum the value for notice.read_num
     *
     * @mbggenerated Wed Jan 24 13:41:17 CST 2018
     */
    public void setReadNum(Integer readNum) {
        this.readNum = readNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.endtime
     *
     * @return the value of notice.endtime
     *
     * @mbggenerated Wed Jan 24 13:41:17 CST 2018
     */
    public String getEndtime() {
        return endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.endtime
     *
     * @param endtime the value for notice.endtime
     *
     * @mbggenerated Wed Jan 24 13:41:17 CST 2018
     */
    public void setEndtime(String endtime) {
        this.endtime = endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.redu1
     *
     * @return the value of notice.redu1
     *
     * @mbggenerated Wed Jan 24 13:41:17 CST 2018
     */
    public String getRedu1() {
        return redu1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.redu1
     *
     * @param redu1 the value for notice.redu1
     *
     * @mbggenerated Wed Jan 24 13:41:17 CST 2018
     */
    public void setRedu1(String redu1) {
        this.redu1 = redu1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.redu2
     *
     * @return the value of notice.redu2
     *
     * @mbggenerated Wed Jan 24 13:41:17 CST 2018
     */
    public String getRedu2() {
        return redu2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.redu2
     *
     * @param redu2 the value for notice.redu2
     *
     * @mbggenerated Wed Jan 24 13:41:17 CST 2018
     */
    public void setRedu2(String redu2) {
        this.redu2 = redu2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.redu3
     *
     * @return the value of notice.redu3
     *
     * @mbggenerated Wed Jan 24 13:41:17 CST 2018
     */
    public String getRedu3() {
        return redu3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.redu3
     *
     * @param redu3 the value for notice.redu3
     *
     * @mbggenerated Wed Jan 24 13:41:17 CST 2018
     */
    public void setRedu3(String redu3) {
        this.redu3 = redu3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.redu4
     *
     * @return the value of notice.redu4
     *
     * @mbggenerated Wed Jan 24 13:41:17 CST 2018
     */
    public String getRedu4() {
        return redu4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.redu4
     *
     * @param redu4 the value for notice.redu4
     *
     * @mbggenerated Wed Jan 24 13:41:17 CST 2018
     */
    public void setRedu4(String redu4) {
        this.redu4 = redu4;
    }
}