package com.wewin.entity;

import org.springframework.stereotype.Component;

@Component
public class NoticeMember {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column noticemember.id
     *
     * @mbggenerated Wed Jan 24 13:41:17 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column noticemember.openid
     *
     * @mbggenerated Wed Jan 24 13:41:17 CST 2018
     */
    private String openid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column noticemember.noticeid
     *
     * @mbggenerated Wed Jan 24 13:41:17 CST 2018
     */
    private Integer noticeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column noticemember.read
     *
     * @mbggenerated Wed Jan 24 13:41:17 CST 2018
     */
    private Integer read;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column noticemember.redu1
     *
     * @mbggenerated Wed Jan 24 13:41:17 CST 2018
     */
    private String redu1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column noticemember.redu2
     *
     * @mbggenerated Wed Jan 24 13:41:17 CST 2018
     */
    private String redu2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column noticemember.redu3
     *
     * @mbggenerated Wed Jan 24 13:41:17 CST 2018
     */
    private String redu3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column noticemember.redu4
     *
     * @mbggenerated Wed Jan 24 13:41:17 CST 2018
     */
    private String redu4;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column noticemember.id
     *
     * @return the value of noticemember.id
     *
     * @mbggenerated Wed Jan 24 13:41:17 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column noticemember.id
     *
     * @param id the value for noticemember.id
     *
     * @mbggenerated Wed Jan 24 13:41:17 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column noticemember.openid
     *
     * @return the value of noticemember.openid
     *
     * @mbggenerated Wed Jan 24 13:41:17 CST 2018
     */
    public String getOpenid() {
        return openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column noticemember.openid
     *
     * @param openid the value for noticemember.openid
     *
     * @mbggenerated Wed Jan 24 13:41:17 CST 2018
     */
    public void setOpenid(String openid) {
        this.openid = openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column noticemember.noticeid
     *
     * @return the value of noticemember.noticeid
     *
     * @mbggenerated Wed Jan 24 13:41:17 CST 2018
     */
    public Integer getNoticeid() {
        return noticeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column noticemember.noticeid
     *
     * @param noticeid the value for noticemember.noticeid
     *
     * @mbggenerated Wed Jan 24 13:41:17 CST 2018
     */
    public void setNoticeid(Integer noticeid) {
        this.noticeid = noticeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column noticemember.read
     *
     * @return the value of noticemember.read
     *
     * @mbggenerated Wed Jan 24 13:41:17 CST 2018
     */
    public Integer getRead() {
        return read;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column noticemember.read
     *
     * @param read the value for noticemember.read
     *
     * @mbggenerated Wed Jan 24 13:41:17 CST 2018
     */
    public void setRead(Integer read) {
        this.read = read;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column noticemember.redu1
     *
     * @return the value of noticemember.redu1
     *
     * @mbggenerated Wed Jan 24 13:41:17 CST 2018
     */
    public String getRedu1() {
        return redu1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column noticemember.redu1
     *
     * @param redu1 the value for noticemember.redu1
     *
     * @mbggenerated Wed Jan 24 13:41:17 CST 2018
     */
    public void setRedu1(String redu1) {
        this.redu1 = redu1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column noticemember.redu2
     *
     * @return the value of noticemember.redu2
     *
     * @mbggenerated Wed Jan 24 13:41:17 CST 2018
     */
    public String getRedu2() {
        return redu2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column noticemember.redu2
     *
     * @param redu2 the value for noticemember.redu2
     *
     * @mbggenerated Wed Jan 24 13:41:17 CST 2018
     */
    public void setRedu2(String redu2) {
        this.redu2 = redu2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column noticemember.redu3
     *
     * @return the value of noticemember.redu3
     *
     * @mbggenerated Wed Jan 24 13:41:17 CST 2018
     */
    public String getRedu3() {
        return redu3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column noticemember.redu3
     *
     * @param redu3 the value for noticemember.redu3
     *
     * @mbggenerated Wed Jan 24 13:41:17 CST 2018
     */
    public void setRedu3(String redu3) {
        this.redu3 = redu3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column noticemember.redu4
     *
     * @return the value of noticemember.redu4
     *
     * @mbggenerated Wed Jan 24 13:41:17 CST 2018
     */
    public String getRedu4() {
        return redu4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column noticemember.redu4
     *
     * @param redu4 the value for noticemember.redu4
     *
     * @mbggenerated Wed Jan 24 13:41:17 CST 2018
     */
    public void setRedu4(String redu4) {
        this.redu4 = redu4;
    }
}