package com.wewin.entity;

import org.springframework.stereotype.Component;

@Component
public class UserInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yhxx.openid
     *
     * @mbggenerated Sat Dec 23 22:07:39 GMT+08:00 2017
     */
    private String openid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yhxx.nickname
     *
     * @mbggenerated Sat Dec 23 22:07:39 GMT+08:00 2017
     */
    private String nickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yhxx.school
     *
     * @mbggenerated Sat Dec 23 22:07:39 GMT+08:00 2017
     */
    private String school;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yhxx.studentno
     *
     * @mbggenerated Sat Dec 23 22:07:39 GMT+08:00 2017
     */
    private String studentno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yhxx.phoneno
     *
     * @mbggenerated Sat Dec 23 22:07:39 GMT+08:00 2017
     */
    private String phoneno;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yhxx.openid
     *
     * @return the value of yhxx.openid
     *
     * @mbggenerated Sat Dec 23 22:07:39 GMT+08:00 2017
     */
    private String unionid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yhxx.avatar
     *
     * @mbggenerated Wed Jan 24 15:59:37 GMT+08:00 2018
     */
    private String avatar;

    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }

    public String getAvatar() {
        return avatar;
    }

    public void setUnionid(String unionid) {
        this.unionid = unionid;
    }

    public String getUnionid() {
        return unionid;
    }

    public String getOpenid() {
        return openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yhxx.openid
     *
     * @param openid the value for yhxx.openid
     *
     * @mbggenerated Sat Dec 23 22:07:39 GMT+08:00 2017
     */
    public void setOpenid(String openid) {
        this.openid = openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yhxx.nickname
     *
     * @return the value of yhxx.nickname
     *
     * @mbggenerated Sat Dec 23 22:07:39 GMT+08:00 2017
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yhxx.nickname
     *
     * @param nickname the value for yhxx.nickname
     *
     * @mbggenerated Sat Dec 23 22:07:39 GMT+08:00 2017
     */
    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yhxx.school
     *
     * @return the value of yhxx.school
     *
     * @mbggenerated Sat Dec 23 22:07:39 GMT+08:00 2017
     */
    public String getSchool() {
        return school;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yhxx.school
     *
     * @param school the value for yhxx.school
     *
     * @mbggenerated Sat Dec 23 22:07:39 GMT+08:00 2017
     */
    public void setSchool(String school) {
        this.school = school;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yhxx.studentno
     *
     * @return the value of yhxx.studentno
     *
     * @mbggenerated Sat Dec 23 22:07:39 GMT+08:00 2017
     */
    public String getStudentno() {
        return studentno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yhxx.studentno
     *
     * @param studentno the value for yhxx.studentno
     *
     * @mbggenerated Sat Dec 23 22:07:39 GMT+08:00 2017
     */
    public void setStudentno(String studentno) {
        this.studentno = studentno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yhxx.phoneno
     *
     * @return the value of yhxx.phoneno
     *
     * @mbggenerated Sat Dec 23 22:07:39 GMT+08:00 2017
     */
    public String getPhoneno() {
        return phoneno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yhxx.phoneno
     *
     * @param phoneno the value for yhxx.phoneno
     *
     * @mbggenerated Sat Dec 23 22:07:39 GMT+08:00 2017
     */
    public void setPhoneno(String phoneno) {
        this.phoneno = phoneno;
    }
}