package com.wewin.entity;

import org.springframework.stereotype.Component;

import java.util.List;

@Component
public class UserInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yhxx.openid
     *
     * @mbggenerated Sun Dec 10 00:54:45 GMT+08:00 2017
     */
    private String openid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yhxx.nick_name
     *
     * @mbggenerated Sun Dec 10 00:54:45 GMT+08:00 2017
     */
    private String nickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yhxx.school
     *
     * @mbggenerated Sun Dec 10 00:54:45 GMT+08:00 2017
     */
    private String school;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yhxx.student_no
     *
     * @mbggenerated Sun Dec 10 00:54:45 GMT+08:00 2017
     */
    private String student_no;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yhxx.phone_no
     *
     * @mbggenerated Sun Dec 10 00:54:45 GMT+08:00 2017
     */
    private String phone_no;




    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yhxx.openid
     *
     * @return the value of yhxx.openid
     *
     * @mbggenerated Sun Dec 10 00:54:45 GMT+08:00 2017
     */
    public String getOpenid() {
        return openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yhxx.openid
     *
     * @param openid the value for yhxx.openid
     *
     * @mbggenerated Sun Dec 10 00:54:45 GMT+08:00 2017
     */
    public void setOpenid(String openid) {
        this.openid = openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yhxx.nick_name
     *
     * @return the value of yhxx.nick_name
     *
     * @mbggenerated Sun Dec 10 00:54:45 GMT+08:00 2017
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yhxx.nick_name
     *
     * @param nickname the value for yhxx.nick_name
     *
     * @mbggenerated Sun Dec 10 00:54:45 GMT+08:00 2017
     */
    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yhxx.school
     *
     * @return the value of yhxx.school
     *
     * @mbggenerated Sun Dec 10 00:54:45 GMT+08:00 2017
     */
    public String getSchool() {
        return school;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yhxx.school
     *
     * @param school the value for yhxx.school
     *
     * @mbggenerated Sun Dec 10 00:54:45 GMT+08:00 2017
     */
    public void setSchool(String school) {
        this.school = school;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yhxx.student_no
     *
     * @return the value of yhxx.student_no
     *
     * @mbggenerated Sun Dec 10 00:54:45 GMT+08:00 2017
     */
    public String getStudent_no() {
        return student_no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yhxx.student_no
     *
     * @param student_no the value for yhxx.student_no
     *
     * @mbggenerated Sun Dec 10 00:54:45 GMT+08:00 2017
     */
    public void setStudent_no(String student_no) {
        this.student_no = student_no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yhxx.phone_no
     *
     * @return the value of yhxx.phone_no
     *
     * @mbggenerated Sun Dec 10 00:54:45 GMT+08:00 2017
     */
    public String getPhone_no() {
        return phone_no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yhxx.phone_no
     *
     * @param phone_no the value for yhxx.phone_no
     *
     * @mbggenerated Sun Dec 10 00:54:45 GMT+08:00 2017
     */
    public void setPhone_no(String phone_no) {
        this.phone_no = phone_no;
    }
}